### ISSUE TITLE
Recipe `mongodb::default` Crashes

### ISSUE THREAD

**Issue by yfeldblum** [gchef/mongodb-cookbook#15]
Recipe `mongodb::default` crashes.

```
Chef::Exceptions::ResourceNotFound: Cannot find a resource matching template[/etc/init/mongodb-server.conf] (did you define it first?)
/usr/lib/ruby/gems/1.8/gems/chef-0.10.0/bin/../lib/chef/resource_collection.rb:115:in `lookup'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.0/bin/../lib/chef/resource_collection.rb:182:in `find_resource_by_hash'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.0/bin/../lib/chef/resource_collection.rb:180:in `each'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.0/bin/../lib/chef/resource_collection.rb:180:in `find_resource_by_hash'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.0/bin/../lib/chef/resource_collection.rb:178:in `each'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.0/bin/../lib/chef/resource_collection.rb:178:in `find_resource_by_hash'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.0/bin/../lib/chef/resource_collection.rb:137:in `find'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.0/bin/../lib/chef/resource_collection.rb:134:in `each'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.0/bin/../lib/chef/resource_collection.rb:134:in `find'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.0/bin/../lib/chef/resource.rb:288:in `resources'
/srv/chef/cache/cookbooks/mongodb/libraries/mondogb_process.rb:79:in `mongodb_process'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.0/bin/../lib/chef/mixin/recipe_definition_dsl_core.rb:69:in `instance_eval'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.0/bin/../lib/chef/mixin/recipe_definition_dsl_core.rb:69:in `method_missing'
/srv/chef/cache/cookbooks/mongodb/libraries/mondogb_process.rb:66:in `mongodb_process'
/srv/chef/cache/cookbooks/mongodb/recipes/server.rb:22:in `from_file'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.0/bin/../lib/chef/cookbook_version.rb:578:in `load_recipe'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.0/bin/../lib/chef/mixin/language_include_recipe.rb:40:in `include_recipe'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.0/bin/../lib/chef/mixin/language_include_recipe.rb:27:in `each'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.0/bin/../lib/chef/mixin/language_include_recipe.rb:27:in `include_recipe'
/srv/chef/cache/cookbooks/mongodb/recipes/default.rb:23:in `from_file'
```

Source is a cookbook with the line:

```
include_recipe "mongodb"
```

**Comment by erkki** [comment]
getting the same here... investigating

**Comment by erkki** [comment]
http://wiki.opscode.com/display/chef/Resources
    Warning
    Note that when using the resources syntax, a resource must have already been defined before you can set a notification that points to it. This shortcoming is the reason the new syntax was introduced in Chef 0.9.10.

**Comment by erkki** [comment]
this does not make sense, the templates for sysv or upstart are configured depending on the system_init option but the templates get notified based on whether the source of the installation was apt or sourcecode, not accounting for invalid set of options

cookbooks/mongodb/attributes/mongodb.rb:default[:mongodb][:server][:system_init]           = "sysv"
default.rb:
include_recipe "mongodb::apt"
include_recipe "mongodb::server"

subscribes :restart, resources(:template => "/etc/init.d/#{service_name}") if node[:mongodb][:installed_from] == "src"
subscribes :restart, resources(:template => "/etc/init/#{service_name}.conf") if node[:mongodb][:installed_from] == "apt"

case node[:mongodb][:system_init]
when "upstart"
    template "/etc/init/#{service_name}.conf" do
        source "mongodb.upstart.erb"
        owner "root"
        group "root"
        mode "0644"
        backup false
        variables init_variables
    end

  link "/etc/init.d/#{service_name}" do
    to "/lib/init/upstart-job"
  end
when "sysv"
    template "/etc/init.d/#{service_name}" do
        source "mongodb.init.erb"
        mode "0755"
        backup false
        variables init_variables
    end
end

**Comment by erkki** [comment]
this fixes it for now..

```
+                               subscribes :restart, resources(:template => "/etc/init.d/#{service_name}") if node[:mongodb][:system_init] == 'sysv'
+                               subscribes :restart, resources(:template => "/etc/init/#{service_name}.conf") if node[:mongodb][:system_init] == 'upstart'
```
