### ISSUE TITLE
undefined method `empty?' for true:TrueClass

### ISSUE THREAD

**Issue by erkki** [gchef/mongodb-cookbook#16]
Chef::Mixin::Template::TemplateError (undefined method `empty?' for true:TrueClass) on line #40:

 38:        :verbose, # Verbose logging output.
 39:    ].each do |option|
 40:        if config[option] && !config[option].empty?
 41: %>
 42: <%= option %> = <%= config[option] %>

**Comment by smorodin** [comment]
I think line 40 can be changed to 

if config[option]

which will validate for nil only and I think this is OK for now. I passed this step too, but code is not working because it stacked on another place.
