### ISSUE TITLE
remote_file downloaded again after reboot

### ISSUE THREAD

**Issue by thbar** [gchef/mongodb-cookbook#2]
I noticed that after reboot (tmp content is erased), the source recipe attempts to load the source again. Is that the desired behaviour ?

In my case I just added a guard after action :create_if_missing in remote_file:

```
not_if { `ps -A -o command | grep "[m]ongo"`.include? node[:mongodb][:version] }
```

**Comment by gerhard** [comment]
This is a great idea! I'm going to modify this on my end, but if you bring any new improvements in the future, fork and send patch request ; ).

**Comment by thbar** [comment]
Will do! I wasn't sure it was the "clean" way of doing it, as I'm just learning writing chef cookbooks :)

What would be the clean way to share the guard ? Can we put the guard then the resources inside a guard block ? Or do we have to call the guard from inside ? 

In any case I'll watch your commit and will provide more patches if I have some.

**Comment by gerhard** [comment]
Fixed

**Comment by thbar** [comment]
Thanks!

**Comment by gerhard** [comment]
Yeah, you're right, [this looks better](https://github.com/papercavalier/mongodb-cookbook/commit/7c6774efba2936e458dcc4beb6be7d887b87618c)

**Comment by thbar** [comment]
Btw, I will ask on the irc chef channel what's the most idiomatic way to do this. I suspect there could be some side effects as the resources do not exist at all (in the last commit) when the process is running. I'll keep you posted.

**Comment by gerhard** [comment]
Which resources don't exist?
